In [1]:
import pathlib

import pandas as pd

In [2]:
data_directory = pathlib.Path('Data')

In [3]:
data_directory.exists()

True

In [4]:
data_files = list(data_directory.glob('*weekly-patterns*'))

In [5]:
current_data_file = data_files[0]
current_data_file

WindowsPath('Data/2020-03-30-weekly-patterns_limited.csv.gz')

In [6]:
data = pd.read_csv(current_data_file, compression = 'gzip')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175321 entries, 0 to 175320
Data columns (total 27 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   safegraph_place_id       175321 non-null  object
 1   date_range_start         175321 non-null  object
 2   date_range_end           175321 non-null  object
 3   raw_visit_counts         175321 non-null  int64
 4   raw_visitor_counts       175321 non-null  int64
 5   visits_by_day            175321 non-null  object
 6   visits_by_each_hour      175321 non-null  object
 7   poi_cbg                  175320 non-null  float64
 8   visitor_home_cbgs        175321 non-null  object
 9   visitor_daytime_cbgs     175321 non-null  object
 10  median_dwell             175321 non-null  float64
 11  bucketed_dwell_times     175321 non-null  object
 12  related_same_day_brand   175321 non-null  object
 13  related_same_week_brand  175321 non-null  object
 14  device_type              175321 non-null  object
 15  location_name            175321 non-null  object
 16  top_category             175321 non-null  object
 17  sub_category             175321 non-null  object
 18  naics_code               175321 non-null  float64
 19  latitude                 175321 non-null  float64
 20  longitude                175321 non-null  float64
 21  street_address           175321 non-null  object
 22  city                     175321 non-null  object
 23  region                   175321 non-null  object
 24  postal_code              175321 non-null  int64
 25  iso_country_code         175321 non-null  object
 26  open_hours               73759 non-null   object
dtypes: float64(5), int64(3), object(19)
memory usage: 36.1+ MB

In [8]:
data.head(3)

,safegraph_place_id,date_range_start,date_range_end,raw_visit_counts,raw_visitor_counts,visits_by_day,visits_by_each_hour,poi_cbg,visitor_home_cbgs,visitor_daytime_cbgs,...,sub_category,naics_code,latitude,longitude,street_address,city,region,postal_code,iso_country_code,open_hours
0,sg:00ce97632af64051b449c3b76edadf2f,2020-03-30T00:00:00-04:00,2020-04-06T00:00:00-04:00,5,5,"[2,0,2,1,0,0,0]","[0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",3.600101e+11,{},{},...,Offices of Physicians (except Mental Health Sp...,621111.0,42.717477,-73.809582,110 Wolf Rd,Albany,NY,12205,US,"{ ""Mon"": [[""8:00"", ""16:00""]], ""Tue"": [[""8:00"",..."
1,sg:00d20507d46146f591f0cef75f685475,2020-03-30T00:00:00-06:00,2020-04-06T00:00:00-06:00,2,2,"[0,0,2,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",8.069002e+10,{},{},...,Offices of Mental Health Practitioners (except...,621330.0,40.414696,-105.061940,2216 Scotch Pine Ct,Loveland,CO,80538,US,"{ ""Mon"": [[""9:00"", ""18:00""]], ""Tue"": [[""9:00"",..."
2,sg:01ace0b55236444b860fb0d16d18d8c1,2020-03-30T00:00:00-05:00,2020-04-06T00:00:00-05:00,49,30,"[7,13,8,7,11,3,0]","[0,0,0,0,0,0,0,1,0,0,2,1,0,1,0,2,0,0,0,0,0,0,0...",5.031001e+10,"{""050310009004"":7,""050310009003"":5,""0509301080...","{""050310009004"":8,""050310010002"":4,""0503100100...",...,Offices of Mental Health Practitioners (except...,621330.0,35.819886,-90.444148,208 Cobean Blvd,Lake City,AR,72437,US,"{ ""Mon"": [], ""Tue"": [[""9:00"", ""17:00""]], ""Wed""..."

In [9]:
pd.set_option('display.max_columns', None)

In [10]:
data

,safegraph_place_id,date_range_start,date_range_end,raw_visit_counts,raw_visitor_counts,visits_by_day,visits_by_each_hour,poi_cbg,visitor_home_cbgs,visitor_daytime_cbgs,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,location_name,top_category,sub_category,naics_code,latitude,longitude,street_address,city,region,postal_code,iso_country_code,open_hours
0,sg:00ce97632af64051b449c3b76edadf2f,2020-03-30T00:00:00-04:00,2020-04-06T00:00:00-04:00,5,5,"[2,0,2,1,0,0,0]","[0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",3.600101e+11,{},{},80.0,"{""<5"":0,""5-20"":1,""21-60"":1,""61-240"":1,"">240"":2}","{""Homewood Suites by Hilton"":100,""Holiday Inn ...","{""Hannaford Supermarkets"":60,""The Vitamin Shop...","{""android"":0,""ios"":0}",Gomez Neurology,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,42.717477,-73.809582,110 Wolf Rd,Albany,NY,12205,US,"{ ""Mon"": [[""8:00"", ""16:00""]], ""Tue"": [[""8:00"",..."
1,sg:00d20507d46146f591f0cef75f685475,2020-03-30T00:00:00-06:00,2020-04-06T00:00:00-06:00,2,2,"[0,0,2,0,0,0,0]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",8.069002e+10,{},{},26.5,"{""<5"":0,""5-20"":0,""21-60"":2,""61-240"":0,"">240"":0}",{},{},"{""android"":0,""ios"":4}",Invision Wellness,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,40.414696,-105.061940,2216 Scotch Pine Ct,Loveland,CO,80538,US,"{ ""Mon"": [[""9:00"", ""18:00""]], ""Tue"": [[""9:00"",..."
2,sg:01ace0b55236444b860fb0d16d18d8c1,2020-03-30T00:00:00-05:00,2020-04-06T00:00:00-05:00,49,30,"[7,13,8,7,11,3,0]","[0,0,0,0,0,0,0,1,0,0,2,1,0,1,0,2,0,0,0,0,0,0,0...",5.031001e+10,"{""050310009004"":7,""050310009003"":5,""0509301080...","{""050310009004"":8,""050310010002"":4,""0503100100...",39.0,"{""<5"":1,""5-20"":18,""21-60"":7,""61-240"":4,"">240"":19}","{""Chevrolet"":14,""Lowe's"":13,""Kum & Go"":8,""Walm...","{""Sonic"":48,""Walmart"":31,""Burger King"":18,""Uni...","{""android"":5,""ios"":22}",A Time For Peace PLLC,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,35.819886,-90.444148,208 Cobean Blvd,Lake City,AR,72437,US,"{ ""Mon"": [], ""Tue"": [[""9:00"", ""17:00""]], ""Wed""..."
3,sg:01cde6127a464257b880d8a075d0a4a0,2020-03-30T00:00:00-04:00,2020-04-06T00:00:00-04:00,27,11,"[5,6,4,5,3,2,2]","[0,0,0,0,0,0,0,1,0,2,0,0,0,0,2,0,0,0,0,0,0,0,0...",1.209900e+11,"{""120990027002"":4,""120990019162"":4}","{""120990019162"":4}",144.0,"{""<5"":0,""5-20"":7,""21-60"":1,""61-240"":8,"">240"":11}",{},"{""BMW"":27,""Rollsâ€‘Royce Motor Cars"":18,""MINI"":1...","{""android"":5,""ios"":8}",Martha Kulig MSW LCSW,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,26.708137,-80.097043,2827 Exchange Ct,West Palm Beach,FL,33409,US,NaN
4,sg:027cd3bb245c4f33824ea01143d04eb1,2020-03-30T00:00:00-04:00,2020-04-06T00:00:00-04:00,12,1,"[0,0,3,3,2,3,1]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",1.210103e+11,{},{},111.5,"{""<5"":0,""5-20"":3,""21-60"":1,""61-240"":7,"">240"":1}",{},{},"{""android"":0,""ios"":0}",Healing the Eye &amp Wellness Center,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,28.185794,-82.152143,40122 Mason Rd,Zephyrhills,FL,33540,US,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175316,sg:fc051e8d3b4240d296ba70c7beb81395,2020-03-30T00:00:00-04:00,2020-04-06T00:00:00-04:00,7,6,"[4,1,1,1,0,0,0]","[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,2,0,0...",2.500565e+11,"{""250056531013"":4,""250056506003"":4}","{""250056506003"":4}",13.0,"{""<5"":0,""5-20"":4,""21-60"":2,""61-240"":0,"">240"":1}",{},"{""Market Basket"":17,""Stop & Shop"":16,""Mobil"":1...","{""android"":4,""ios"":4}",Flip Side Sober Housing & Consultations,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,41.665424,-70.925439,60 Hathaway St,New Bedford,MA,2746,US,NaN
175317,sg:fd12ea814fd9460992d6cafdae6d66b8,2020-03-30T00:00:00-05:00,2020-04-06T00:00:00-05:00,18,7,"[4,0,5,5,3,0,1]","[0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0...",2.205500e+11,"{""220550014094"":4,""220979607002"":4,""2205500140...","{""220550014094"":4,""221139509023"":4}",88.5,"{""<5"":0,""5-20"":0,""21-60"":6,""61-240"":8,"">240"":4}","{""McDonald's"":46,""Chevrolet"":20,""Family Dollar...","{""Super 1 Foods & Discount Pharmacy"":43,""Sonic...","{""android"":0,""ios"":6}",Brad Sibille MA LPC S,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,30.163336,-92.044170,200 Beaullieu Dr Bldg 9B-1,Lafayette,LA,70508,US,"{ ""Mon"": [[""8:00"", ""17:00""]], ""Tue"": [[""8:00"",..."
175318,sg:fd3d5562b01a48fa859e936f0ae33d21,2020-03-30T00:00:00-07:00,2020-04-06T00:00:00-07:00,14,5,"[3,1,2,4,4,0,0]","[0,0,0,0,0,0,0,0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0...",6.017031e+10,"{""060170309012"":4}","{""060170314062"":4,""060170309012"":4}",345.0,"{""<5"":0,""5-20"":2,""21-60"":1,""61-240"":2,"">240"":9}","{""Whole Foods Market"":50,""Starbucks"":48}","{""Safeway"":39,""Holiday Market"":20,""T.J. Maxx"":...","{""android"":0,""ios"":0}",Marshall Medical,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,38.726271,-120.789823,3177 Turner St,Placerville,CA,95667,US,NaN
175319,sg:fd56b2f25d48481b9b0b340367499485,2020-03-30T00:00:00-07:00,2020-04-06T00:00:00-07:00,7,3,"[0,1,2,1,3,0,0]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",6.073008e+10,{},"{""060730171102"":4,""060730083471"":4}",389.0,"{""<5"":0,""5-20"":1,""21-60"":2,""61-240"":0,"">240"":4}",{},{},"{""android"":4,""ios"":0}",Angela Winslow MFT Couples Counseling San Diego,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,32.891623,-117.194572,5230 Carroll Canyon Rd Ste 100,San Diego,CA,92121,US,"{ ""Mon"": [[""8:30"", ""19:00""]], ""Tue"": [], ""Wed""..."
175320,sg:fe7e0b9de7384cce9104c15cd11b03c7,2020-03-30T00:00:00-04:00,2020-04-06T00:00:00-04:00,8,7,"[1,1,3,0,2,1,0]","[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",4.400700e+11,{},{},27.0,"{""<5"":0,""5-20"":3,""21-60"":3,""61-240"":1,"">240"":1}","{""McDonald's"":46}","{""Au Bon Pain"":43,""McDonald's"":36,""CVS"":26,""Sh...","{""android"":4,""ios"":0}",Women & Infants Hospital of Rhode Island,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,41.809213,-71.407328,695 Eddy St,Providence,RI,2903,US,NaN

In [12]:
data.loc[0,:].to_dict()

{'safegraph_place_id': 'sg:00bad7fe51214518a50e9f835f895b0b',
 'date_range_start': '2019-12-09T00:00:00-05:00',
 'date_range_end': '2019-12-16T00:00:00-05:00',
 'raw_visit_counts': 4,
 'raw_visitor_counts': 4,
 'visits_by_day': '[1,1,0,0,1,1,0]',
 'visits_by_each_hour': '[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]',
 'poi_cbg': 340350515001.0,
 'visitor_home_cbgs': '{"340350538042":4}',
 'visitor_daytime_cbgs': '{}',
 'median_dwell': 252.5,
 'bucketed_dwell_times': '{"<5":0,"5-20":0,"21-60":1,"61-240":1,">240":2}',
 'related_same_day_brand': '{}',
 'related_same_week_brand': '{}',
 'device_type': '{"android":0,"ios":4}',
 'location_name': 'Foot & Ankle Care Associates',
 'top_category': 'Offices of Physicians',
 'sub_category': 'Offices of Physicians (except Mental Health Specialists)',
 'naics_code': 621111.0,
 'latitude': 40.542393,
 'longitude': -74.587482,
 'street_address': '102 S Main St',
 'city': 'Manville',
 'region': 'NJ',
 'postal_code': 8835,
 'iso_country_code': 'US',
 'open_hours': '{ "Mon": [["8:30", "18:00"]], "Tue": [["8:00", "18:00"]], "Wed": [["14:00", "17:30"]], "Thu": [], "Fri": [["8:30", "17:30"]], "Sat": [], "Sun": [] }'}

In [13]:
type(data.loc[0, 'date_range_start'])

str

In [14]:
pd.to_datetime(data.loc[0, 'date_range_start'])

Timestamp('2019-12-09 00:00:00-0500', tz='pytz.FixedOffset(-300)')

In [15]:
data['date_range_start'] = data['date_range_start'].str.split('T', expand = True)[0]

In [16]:
pd.to_datetime(data['date_range_start'])

0        2019-12-09
1        2019-12-09
2        2019-12-09
3        2019-12-09
4        2019-12-09
            ...
198910   2019-12-09
198911   2019-12-09
198912   2019-12-09
198913   2019-12-09
198914   2019-12-09
Name: date_range_start, Length: 198915, dtype: datetime64[ns]

In [17]:
data.head(5)

,safegraph_place_id,date_range_start,date_range_end,raw_visit_counts,raw_visitor_counts,visits_by_day,visits_by_each_hour,poi_cbg,visitor_home_cbgs,visitor_daytime_cbgs,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,location_name,top_category,sub_category,naics_code,latitude,longitude,street_address,city,region,postal_code,iso_country_code,open_hours
0,sg:00bad7fe51214518a50e9f835f895b0b,2019-12-09,2019-12-16T00:00:00-05:00,4,4,"[1,1,0,0,1,1,0]","[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",3.403505e+11,"{""340350538042"":4}",{},252.5,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":1,"">240"":2}",{},{},"{""android"":0,""ios"":4}",Foot & Ankle Care Associates,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,40.542393,-74.587482,102 S Main St,Manville,NJ,8835,US,"{ ""Mon"": [[""8:30"", ""18:00""]], ""Tue"": [[""8:00"",..."
1,sg:00ce97632af64051b449c3b76edadf2f,2019-12-09,2019-12-16T00:00:00-05:00,6,4,"[1,2,2,0,1,0,0]","[0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",3.600101e+11,"{""360010138012"":4}","{""360010139012"":4}",13.0,"{""<5"":0,""5-20"":4,""21-60"":0,""61-240"":0,"">240"":2}",{},{},"{""android"":4,""ios"":0}",Gomez Neurology,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,42.717477,-73.809582,110 Wolf Rd,Albany,NY,12205,US,"{ ""Mon"": [[""8:00"", ""16:00""]], ""Tue"": [[""8:00"",..."
2,sg:00d20507d46146f591f0cef75f685475,2019-12-09,2019-12-16T00:00:00-07:00,2,2,"[0,0,0,1,1,0,0]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",8.069002e+10,"{""080690020073"":4}","{""080690019024"":4}",201.5,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":2,"">240"":0}",{},{},"{""android"":0,""ios"":4}",Invision Wellness,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,40.414696,-105.061940,2216 Scotch Pine Ct,Loveland,CO,80538,US,"{ ""Mon"": [[""9:00"", ""18:00""]], ""Tue"": [[""9:00"",..."
3,sg:01ace0b55236444b860fb0d16d18d8c1,2019-12-09,2019-12-16T00:00:00-06:00,37,18,"[6,4,6,6,10,2,3]","[0,0,0,0,0,0,0,2,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0...",5.031001e+10,"{""050310010004"":7,""050310008012"":4,""0503100090...","{""050310005011"":4,""050310009004"":4,""0503100100...",97.0,"{""<5"":0,""5-20"":9,""21-60"":4,""61-240"":13,"">240"":11}","{""Olive Garden"":50,""Walmart"":41,""Unico Bank"":2...","{""Walmart"":38,""Sonic"":37,""Wings To Go"":22,""Uni...","{""android"":0,""ios"":8}",A Time For Peace PLLC,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,35.819886,-90.444148,208 Cobean Blvd,Lake City,AR,72437,US,"{ ""Mon"": [], ""Tue"": [[""9:00"", ""17:00""]], ""Wed""..."
4,sg:01cde6127a464257b880d8a075d0a4a0,2019-12-09,2019-12-16T00:00:00-05:00,69,42,"[16,10,11,8,18,1,5]","[3,1,1,0,0,0,0,1,1,2,1,0,0,0,0,0,0,0,0,1,1,3,0...",1.209900e+11,"{""120990020051"":12,""120990078313"":4,""120990031...","{""120990020051"":10,""120990019161"":4,""120990018...",95.0,"{""<5"":1,""5-20"":15,""21-60"":13,""61-240"":16,"">240...","{""CVS"":9,""Porsche"":7}","{""Rollsâ€‘Royce Motor Cars"":7,""MINI"":7,""BMW"":7}","{""android"":19,""ios"":19}",Martha Kulig MSW LCSW,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,26.708137,-80.097043,2827 Exchange Ct,West Palm Beach,FL,33409,US,NaN

In [18]:
data.loc[0,'visits_by_day']

'[1,1,0,0,1,1,0]'

In [19]:
import json

In [20]:
type(json.loads(data.loc[0,'visits_by_day']))

list

In [21]:
data['visits_by_day'] = data['visits_by_day'].str.replace('[','')\
.str.replace(']','').str.split(',')

C:\Users\jbrun\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.
C:\Users\jbrun\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.

In [22]:
type(data.loc[0,'visits_by_day'])

list

In [23]:
data.loc[4,'visitor_home_cbgs']

'{"120990020051":12,"120990078313":4,"120990031011":4,"120990034001":4,"120990002092":4}'

In [24]:
json.loads(data.loc[4,'visitor_home_cbgs'])

{'120990020051': 12,
 '120990078313': 4,
 '120990031011': 4,
 '120990034001': 4,
 '120990002092': 4}

In [25]:
import time

In [26]:
start_time = time.time()

converted_col = [json.loads(dict_string) for dict_string in data['visitor_home_cbgs'].tolist()]

end_time = time.time()

print(f'Took {round(end_time - start_time)} seconds')

Took 1 seconds

In [27]:
data.loc[4,:]

safegraph_place_id                       sg:01cde6127a464257b880d8a075d0a4a0
date_range_start                                                  2019-12-09
date_range_end                                     2019-12-16T00:00:00-05:00
raw_visit_counts                                                          69
raw_visitor_counts                                                        42
visits_by_day                                      [16, 10, 11, 8, 18, 1, 5]
visits_by_each_hour        [3,1,1,0,0,0,0,1,1,2,1,0,0,0,0,0,0,0,0,1,1,3,0...
poi_cbg                                                       120990020051.0
visitor_home_cbgs          {"120990020051":12,"120990078313":4,"120990031...
visitor_daytime_cbgs       {"120990020051":10,"120990019161":4,"120990018...
median_dwell                                                            95.0
bucketed_dwell_times       {"<5":1,"5-20":15,"21-60":13,"61-240":16,">240...
related_same_day_brand                                 {"CVS":9,"Porsche":7}
related_same_week_brand        {"Rollsâ€‘Royce Motor Cars":7,"MINI":7,"BMW":7}
device_type                                          {"android":19,"ios":19}
location_name                                          Martha Kulig MSW LCSW
top_category                           Offices of Other Health Practitioners
sub_category               Offices of Mental Health Practitioners (except...
naics_code                                                          621330.0
latitude                                                           26.708137
longitude                                                         -80.097043
street_address                                              2827 Exchange Ct
city                                                         West Palm Beach
region                                                                    FL
postal_code                                                            33409
iso_country_code                                                          US
open_hours                                                               NaN
Name: 4, dtype: object

In [28]:
cbg = pd.read_csv('https://www2.census.gov/geo/docs/reference/cenpop2010/blkgrp/CenPop2010_Mean_BG12.txt')

In [29]:
cbg['COUNTYFP'].astype(str).str.zfill(3)

0        001
1        001
2        001
3        001
4        001
        ...
11437    133
11438    133
11439    133
11440    133
11441    133
Name: COUNTYFP, Length: 11442, dtype: object

In [30]:
cbg.head(2)

   STATEFP  COUNTYFP  TRACTCE  BLKGRPCE  POPULATION   LATITUDE  LONGITUDE
0       12         1      200         1         710  29.656278 -82.329388
1       12         1      200         2        1391  29.647973 -82.329713

In [31]:
width_mapper = {
    'STATEFP': 2,
    'COUNTYFP': 3,
    'TRACTCE': 6,
    'BLKGRPCE': 1,
}

for key, val in width_mapper.items():
    cbg[key] = cbg[key].astype(str).str.zfill(val)

cbg.head(2)

  STATEFP COUNTYFP TRACTCE BLKGRPCE  POPULATION   LATITUDE  LONGITUDE
0      12      001  000200        1         710  29.656278 -82.329388
1      12      001  000200        2        1391  29.647973 -82.329713

In [32]:
cbg['STATEFP'] + cbg['COUNTYFP'] + cbg['TRACTCE'] + cbg['BLKGRPCE']

0        120010002001
1        120010002002
2        120010002003
3        120010002004
4        120010002005
             ...
11437    121339703021
11438    121339703022
11439    121339703023
11440    121339703031
11441    121339703032
Length: 11442, dtype: object

In [33]:
cbg.head()

  STATEFP COUNTYFP TRACTCE BLKGRPCE  POPULATION   LATITUDE  LONGITUDE
0      12      001  000200        1         710  29.656278 -82.329388
1      12      001  000200        2        1391  29.647973 -82.329713
2      12      001  000200        3         911  29.657112 -82.336791
3      12      001  000200        4         866  29.651747 -82.335036
4      12      001  000200        5         798  29.649917 -82.338222

In [34]:
data.rename({'' 'postal_code': 'GeoFips'}, axis=1, inplace=True)
data

,safegraph_place_id,date_range_start,date_range_end,raw_visit_counts,raw_visitor_counts,visits_by_day,visits_by_each_hour,poi_cbg,visitor_home_cbgs,visitor_daytime_cbgs,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,location_name,top_category,sub_category,naics_code,latitude,longitude,street_address,city,region,GeoFips,iso_country_code,open_hours
0,sg:00bad7fe51214518a50e9f835f895b0b,2019-12-09,2019-12-16T00:00:00-05:00,4,4,"[1, 1, 0, 0, 1, 1, 0]","[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",3.403505e+11,"{""340350538042"":4}",{},252.5,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":1,"">240"":2}",{},{},"{""android"":0,""ios"":4}",Foot & Ankle Care Associates,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,40.542393,-74.587482,102 S Main St,Manville,NJ,8835,US,"{ ""Mon"": [[""8:30"", ""18:00""]], ""Tue"": [[""8:00"",..."
1,sg:00ce97632af64051b449c3b76edadf2f,2019-12-09,2019-12-16T00:00:00-05:00,6,4,"[1, 2, 2, 0, 1, 0, 0]","[0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",3.600101e+11,"{""360010138012"":4}","{""360010139012"":4}",13.0,"{""<5"":0,""5-20"":4,""21-60"":0,""61-240"":0,"">240"":2}",{},{},"{""android"":4,""ios"":0}",Gomez Neurology,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,42.717477,-73.809582,110 Wolf Rd,Albany,NY,12205,US,"{ ""Mon"": [[""8:00"", ""16:00""]], ""Tue"": [[""8:00"",..."
2,sg:00d20507d46146f591f0cef75f685475,2019-12-09,2019-12-16T00:00:00-07:00,2,2,"[0, 0, 0, 1, 1, 0, 0]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",8.069002e+10,"{""080690020073"":4}","{""080690019024"":4}",201.5,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":2,"">240"":0}",{},{},"{""android"":0,""ios"":4}",Invision Wellness,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,40.414696,-105.061940,2216 Scotch Pine Ct,Loveland,CO,80538,US,"{ ""Mon"": [[""9:00"", ""18:00""]], ""Tue"": [[""9:00"",..."
3,sg:01ace0b55236444b860fb0d16d18d8c1,2019-12-09,2019-12-16T00:00:00-06:00,37,18,"[6, 4, 6, 6, 10, 2, 3]","[0,0,0,0,0,0,0,2,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0...",5.031001e+10,"{""050310010004"":7,""050310008012"":4,""0503100090...","{""050310005011"":4,""050310009004"":4,""0503100100...",97.0,"{""<5"":0,""5-20"":9,""21-60"":4,""61-240"":13,"">240"":11}","{""Olive Garden"":50,""Walmart"":41,""Unico Bank"":2...","{""Walmart"":38,""Sonic"":37,""Wings To Go"":22,""Uni...","{""android"":0,""ios"":8}",A Time For Peace PLLC,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,35.819886,-90.444148,208 Cobean Blvd,Lake City,AR,72437,US,"{ ""Mon"": [], ""Tue"": [[""9:00"", ""17:00""]], ""Wed""..."
4,sg:01cde6127a464257b880d8a075d0a4a0,2019-12-09,2019-12-16T00:00:00-05:00,69,42,"[16, 10, 11, 8, 18, 1, 5]","[3,1,1,0,0,0,0,1,1,2,1,0,0,0,0,0,0,0,0,1,1,3,0...",1.209900e+11,"{""120990020051"":12,""120990078313"":4,""120990031...","{""120990020051"":10,""120990019161"":4,""120990018...",95.0,"{""<5"":1,""5-20"":15,""21-60"":13,""61-240"":16,"">240...","{""CVS"":9,""Porsche"":7}","{""Rollsâ€‘Royce Motor Cars"":7,""MINI"":7,""BMW"":7}","{""android"":19,""ios"":19}",Martha Kulig MSW LCSW,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,26.708137,-80.097043,2827 Exchange Ct,West Palm Beach,FL,33409,US,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198910,sg:fc051e8d3b4240d296ba70c7beb81395,2019-12-09,2019-12-16T00:00:00-05:00,50,25,"[0, 2, 6, 8, 8, 11, 15]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",2.500565e+11,"{""250056531013"":5,""250056506003"":5,""2500565070...","{""250056511004"":4,""250056506003"":4}",140.0,"{""<5"":0,""5-20"":11,""21-60"":8,""61-240"":21,"">240""...","{""Healthtrax Fitness & Wellness"":12}","{""Dunkin'"":18,""Shaw's"":12,""Cumberland Farms"":1...","{""android"":19,""ios"":4}",Flip Side Sober Housing & Consultations,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,41.665424,-70.925439,60 Hathaway St,New Bedford,MA,2746,US,NaN
198911,sg:fd12ea814fd9460992d6cafdae6d66b8,2019-12-09,2019-12-16T00:00:00-06:00,16,14,"[3, 2, 4, 6, 1, 0, 0]","[0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0...",2.205500e+11,"{""220550019042"":4,""220550014094"":4}",{},58.0,"{""<5"":0,""5-20"":4,""21-60"":4,""61-240"":4,"">240"":4}","{""Starbucks"":48}","{""Chick-fil-A"":39,""Starbucks"":29,""Academy Spor...","{""android"":0,""ios"":12}",Brad Sibille MA LPC S,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,30.163336,-92.044170,200 Beaullieu Dr Bldg 9B-1,Lafayette,LA,70508,US,"{ ""Mon"": [[""8:00"", ""17:00""]], ""Tue"": [[""8:00"",..."
198912,sg:fd3d5562b01a48fa859e936f0ae33d21,2019-12-09,2019-12-16T00:00:00-08:00,35,14,"[8, 5, 9, 4, 9, 0, 0]","[0,0,0,0,0,0,0,0,3,0,0,0,0,3,1,0,1,0,0,0,0,0,0...",6.017031e+10,"{""060170314062"":4,""060170310003"":4,""0601703150...","{""060670085083"":4,""060170310003"":4,""0601703110...",117.0,"{""<5"":0,""5-20"":5,""21-60"":7,""61-240"":14,"">240"":9}","{""Cadence Academy Preschool"":33,""Safeway"":33,""...","{""Starbucks"":22,""Safeway"":21,""Ross Stores"":20,...","{""android"":4,""ios"":10}",Marshall Medical,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,38.726271,-120.789823,3177 Turner St,Placerville,CA,95667,US,NaN
198913,sg:fd56b2f25d48481b9b0b340367499485,2019-12-09,2019-12-16T00:00:00-08:00,17,15,"[1, 4, 2, 3, 3, 2, 2]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0...",6.073008e+10,"{""060730215001"":5,""060730069003"":5,""0607300833...","{""060730215001"":5,""060730083461"":4,""0607301704...",79.0,"{""<5"":0,""5-20"":2,""21-60"":6,""61-240"":6,"">240"":3}",{},"{""Vons"":27,""Shell Oil"":16,""Sprouts Farmers Mar...","{""android"":10,""ios"":7}",Angela Winslow MFT Couples Counseling San Diego,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,32.891623,-117.194572,5230 Carroll Canyon Rd Ste 100,San Diego,CA,92121,US,"{ ""Mon"": [[""8:30"", ""19:00""]], ""Tue"": [], ""Wed""..."
198914,sg:fe7e0b9de7384cce9104c15cd11b03c7,2019-12-09,2019-12-16T00:00:00-05:00,9,9,"[0, 1, 2, 4, 2, 0, 0]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",4.400700e+11,"{""440070127023"":5,""440070028001"":4}","{""250056302002"":4,""440070105021"":4}",9.0,"{""<5"":1,""5-20"":7,""21-60"":0,""61-240"":0,"">240"":1}",{},"{""Au Bon Pain"":33,""CVS"":30,""Walmart"":16,""Ocean...","{""android"":7,""ios"":4}",Women & Infants Hospital of Rhode Island,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,41.809213,-71.407328,695 Eddy St,Providence,RI,2903,US,NaN

In [35]:
data.head()

,safegraph_place_id,date_range_start,date_range_end,raw_visit_counts,raw_visitor_counts,visits_by_day,visits_by_each_hour,poi_cbg,visitor_home_cbgs,visitor_daytime_cbgs,median_dwell,bucketed_dwell_times,related_same_day_brand,related_same_week_brand,device_type,location_name,top_category,sub_category,naics_code,latitude,longitude,street_address,city,region,GeoFips,iso_country_code,open_hours
0,sg:00bad7fe51214518a50e9f835f895b0b,2019-12-09,2019-12-16T00:00:00-05:00,4,4,"[1, 1, 0, 0, 1, 1, 0]","[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",3.403505e+11,"{""340350538042"":4}",{},252.5,"{""<5"":0,""5-20"":0,""21-60"":1,""61-240"":1,"">240"":2}",{},{},"{""android"":0,""ios"":4}",Foot & Ankle Care Associates,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,40.542393,-74.587482,102 S Main St,Manville,NJ,8835,US,"{ ""Mon"": [[""8:30"", ""18:00""]], ""Tue"": [[""8:00"",..."
1,sg:00ce97632af64051b449c3b76edadf2f,2019-12-09,2019-12-16T00:00:00-05:00,6,4,"[1, 2, 2, 0, 1, 0, 0]","[0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",3.600101e+11,"{""360010138012"":4}","{""360010139012"":4}",13.0,"{""<5"":0,""5-20"":4,""21-60"":0,""61-240"":0,"">240"":2}",{},{},"{""android"":4,""ios"":0}",Gomez Neurology,Offices of Physicians,Offices of Physicians (except Mental Health Sp...,621111.0,42.717477,-73.809582,110 Wolf Rd,Albany,NY,12205,US,"{ ""Mon"": [[""8:00"", ""16:00""]], ""Tue"": [[""8:00"",..."
2,sg:00d20507d46146f591f0cef75f685475,2019-12-09,2019-12-16T00:00:00-07:00,2,2,"[0, 0, 0, 1, 1, 0, 0]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",8.069002e+10,"{""080690020073"":4}","{""080690019024"":4}",201.5,"{""<5"":0,""5-20"":0,""21-60"":0,""61-240"":2,"">240"":0}",{},{},"{""android"":0,""ios"":4}",Invision Wellness,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,40.414696,-105.061940,2216 Scotch Pine Ct,Loveland,CO,80538,US,"{ ""Mon"": [[""9:00"", ""18:00""]], ""Tue"": [[""9:00"",..."
3,sg:01ace0b55236444b860fb0d16d18d8c1,2019-12-09,2019-12-16T00:00:00-06:00,37,18,"[6, 4, 6, 6, 10, 2, 3]","[0,0,0,0,0,0,0,2,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0...",5.031001e+10,"{""050310010004"":7,""050310008012"":4,""0503100090...","{""050310005011"":4,""050310009004"":4,""0503100100...",97.0,"{""<5"":0,""5-20"":9,""21-60"":4,""61-240"":13,"">240"":11}","{""Olive Garden"":50,""Walmart"":41,""Unico Bank"":2...","{""Walmart"":38,""Sonic"":37,""Wings To Go"":22,""Uni...","{""android"":0,""ios"":8}",A Time For Peace PLLC,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,35.819886,-90.444148,208 Cobean Blvd,Lake City,AR,72437,US,"{ ""Mon"": [], ""Tue"": [[""9:00"", ""17:00""]], ""Wed""..."
4,sg:01cde6127a464257b880d8a075d0a4a0,2019-12-09,2019-12-16T00:00:00-05:00,69,42,"[16, 10, 11, 8, 18, 1, 5]","[3,1,1,0,0,0,0,1,1,2,1,0,0,0,0,0,0,0,0,1,1,3,0...",1.209900e+11,"{""120990020051"":12,""120990078313"":4,""120990031...","{""120990020051"":10,""120990019161"":4,""120990018...",95.0,"{""<5"":1,""5-20"":15,""21-60"":13,""61-240"":16,"">240...","{""CVS"":9,""Porsche"":7}","{""Rollsâ€‘Royce Motor Cars"":7,""MINI"":7,""BMW"":7}","{""android"":19,""ios"":19}",Martha Kulig MSW LCSW,Offices of Other Health Practitioners,Offices of Mental Health Practitioners (except...,621330.0,26.708137,-80.097043,2827 Exchange Ct,West Palm Beach,FL,33409,US,NaN

In [36]:
base_url = 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv'

all_data =pd.read_csv(base_url)
all_data

               date      county       state     fips  cases  deaths
0        2020-01-21   Snohomish  Washington  53061.0      1     0.0
1        2020-01-22   Snohomish  Washington  53061.0      1     0.0
2        2020-01-23   Snohomish  Washington  53061.0      1     0.0
3        2020-01-24        Cook    Illinois  17031.0      1     0.0
4        2020-01-24   Snohomish  Washington  53061.0      1     0.0
...             ...         ...         ...      ...    ...     ...
1014578  2021-02-09  Sweetwater     Wyoming  56037.0   3561    34.0
1014579  2021-02-09       Teton     Wyoming  56039.0   3266     9.0
1014580  2021-02-09       Uinta     Wyoming  56041.0   1994    12.0
1014581  2021-02-09    Washakie     Wyoming  56043.0    869    26.0
1014582  2021-02-09      Weston     Wyoming  56045.0    618     5.0

[1014583 rows x 6 columns]

In [37]:
all_data.rename({'fips': 'GeoFips'}, axis=1, inplace=True)

In [ ]:
df = pd.merge(data, all_data, how="left", on=["GeoFips","date"])
df

In [47]:
df.dropna(subset = ["deaths", "cases"], inplace=True)
df

,date_range_start,date_range_end,raw_visit_counts,raw_visitor_counts,top_category,latitude,longitude,city,region,GeoFips,iso_country_code,county,state,cases,deaths
7,2019-12-09,2019-12-16T00:00:00-05:00,106,79,Offices of Physicians,39.350163,-76.477246,Rosedale,MD,21237,US,Wolfe,Kentucky,1.0,0.0
8,2019-12-09,2019-12-16T00:00:00-05:00,106,79,Offices of Physicians,39.350163,-76.477246,Rosedale,MD,21237,US,Wolfe,Kentucky,1.0,0.0
9,2019-12-09,2019-12-16T00:00:00-05:00,106,79,Offices of Physicians,39.350163,-76.477246,Rosedale,MD,21237,US,Wolfe,Kentucky,1.0,0.0
10,2019-12-09,2019-12-16T00:00:00-05:00,106,79,Offices of Physicians,39.350163,-76.477246,Rosedale,MD,21237,US,Wolfe,Kentucky,1.0,0.0
11,2019-12-09,2019-12-16T00:00:00-05:00,106,79,Offices of Physicians,39.350163,-76.477246,Rosedale,MD,21237,US,Wolfe,Kentucky,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3464490,2019-12-09,2019-12-16T00:00:00-05:00,8,6,Offices of Other Health Practitioners,39.891446,-74.861381,Medford,NJ,8055,US,Huerfano,Colorado,293.0,17.0
3464491,2019-12-09,2019-12-16T00:00:00-05:00,8,6,Offices of Other Health Practitioners,39.891446,-74.861381,Medford,NJ,8055,US,Huerfano,Colorado,293.0,17.0
3464492,2019-12-09,2019-12-16T00:00:00-05:00,8,6,Offices of Other Health Practitioners,39.891446,-74.861381,Medford,NJ,8055,US,Huerfano,Colorado,294.0,17.0
3464493,2019-12-09,2019-12-16T00:00:00-05:00,8,6,Offices of Other Health Practitioners,39.891446,-74.861381,Medford,NJ,8055,US,Huerfano,Colorado,294.0,17.0
3464494,2019-12-09,2019-12-16T00:00:00-05:00,8,6,Offices of Other Health Practitioners,39.891446,-74.861381,Medford,NJ,8055,US,Huerfano,Colorado,294.0,17.0

In [ ]:
df = df.drop(df.columns[[0, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 21, 26, 27]], axis=1)

In [46]:
df.dtypes

date_range_start       object
date_range_end         object
raw_visit_counts        int64
raw_visitor_counts      int64
top_category           object
latitude              float64
longitude             float64
city                   object
region                 object
GeoFips                 int64
iso_country_code       object
county                 object
state                  object
cases                 float64
deaths                float64
dtype: object

In [55]:
df.groupby(["GeoFips",], as_index=False)["cases"].sum()

     GeoFips      cases
0       1001  2898360.0
1       1005   492524.0
2       1007  1642893.0
3       1013  1081756.0
4       1027  1115856.0
..       ...        ...
819    56009    85425.0
820    56011    76382.0
821    56013  1379715.0
822    56031   440950.0
823    78010   123258.0

[824 rows x 2 columns]

In [54]:
df.groupby(["GeoFips",], as_index=False)["raw_visit_counts"].sum()

     GeoFips  raw_visit_counts
0       1001             33269
1       1005             13772
2       1007             29481
3       1013             37996
4       1027             32200
..       ...               ...
819    56009               638
820    56011              4056
821    56013             75818
822    56031             92750
823    78010             19840

[824 rows x 2 columns]

In [58]:
df['date_range_start'] = pd.to_datetime(df['date_range_start'])
df = df[df['date_range_start'] > pd.to_datetime('2019-12-09')]

In [59]:
df

Empty DataFrame
Columns: [date_range_start, date_range_end, raw_visit_counts, raw_visitor_counts, top_category, latitude, longitude, city, region, GeoFips, iso_country_code, county, state, cases, deaths]
Index: []

In [57]:
top_categories = df.groupby('top_category')['raw_visit_counts'].sum().nlargest(25).index.tolist()
myfilter = df['top_category'].isin(top_categories)
df = df[myfilter]

df = df.reset_index(drop = True)

In [ ]:
# want to do an animated choropleth map (next step from previous twitter map but can I show over time well with this data?)